In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("SuperStore_Sales_Dataset.csv")
df.head()

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
0,4918,CA-2019-160304,01-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.94,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.94,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,02-01-2019,07-01-2019,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.98,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,03-01-2019,05-01-2019,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.46,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,03-01-2019,08-01-2019,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.08,2,-5.2640,NaN,Online,NaN,NaN

In [3]:
df.describe()

,Row ID+O6G3A1:R6,Sales,Quantity,Profit,Returns,ind1,ind2
count,5901.000000,5901.000000,5901.000000,5901.000000,287.0,0.0,0.0
mean,5022.422471,265.345589,3.781901,29.700408,1.0,NaN,NaN
std,2877.977184,474.260645,2.212917,259.589138,0.0,NaN,NaN
min,1.000000,0.836000,1.000000,-6599.978000,1.0,NaN,NaN
25%,2486.000000,71.976000,2.000000,1.795500,1.0,NaN,NaN
50%,5091.000000,128.648000,3.000000,8.502500,1.0,NaN,NaN
75%,7456.000000,265.170000,5.000000,28.615000,1.0,NaN,NaN
max,9994.000000,9099.930000,14.000000,8399.976000,1.0,NaN,NaN

In [4]:
df.isnull().sum()

Row ID+O6G3A1:R6       0
Order ID               0
Order Date             0
Ship Date              0
Ship Mode              0
Customer ID            0
Customer Name          0
Segment                0
Country                0
City                   0
State                  0
Region                 0
Product ID             0
Category               0
Sub-Category           0
Product Name           0
Sales                  0
Quantity               0
Profit                 0
Returns             5614
Payment Mode           0
ind1                5901
ind2                5901
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5901 entries, 0 to 5900
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Row ID+O6G3A1:R6  5901 non-null   int64
 1   Order ID          5901 non-null   object
 2   Order Date        5901 non-null   object
 3   Ship Date         5901 non-null   object
 4   Ship Mode         5901 non-null   object
 5   Customer ID       5901 non-null   object
 6   Customer Name     5901 non-null   object
 7   Segment           5901 non-null   object
 8   Country           5901 non-null   object
 9   City              5901 non-null   object
 10  State             5901 non-null   object
 11  Region            5901 non-null   object
 12  Product ID        5901 non-null   object
 13  Category          5901 non-null   object
 14  Sub-Category      5901 non-null   object
 15  Product Name      5901 non-null   object
 16  Sales             5901 non-null   float64
 17  Quantity          5901 non-null   int64
 18  Profit            5901 non-null   float64
 19  Returns           287 non-null    float64
 20  Payment Mode      5901 non-null   object
 21  ind1              0 non-null      float64
 22  ind2              0 non-null      float64
dtypes: float64(5), int64(2), object(16)
memory usage: 1.0+ MB

In [7]:
# CLEANING THE DATA
df = df.dropna(how="all")

In [8]:
df.columns = df.columns.str.strip()

In [9]:
cols = ["Order ID","Order Date","Ship Date","Ship Mode","Customer ID","Customer Name","Segment",
        "Country","City","State","Region","Product ID","Category","Sub-Category","Product Name","Payment Mode"]

In [10]:
for col in cols:
 df[col] = df[col].str.strip()

In [11]:
df.drop(columns=["ind1","ind2"],inplace =True)

In [12]:
df["Returns"] = df["Returns"].fillna(0)

In [13]:
dates = ["Order Date","Ship Date"]
for date in dates:
    df[date] =  pd.to_datetime(df[date],errors = "coerce")
    df[date] = df[date].dt.strftime("%Y-%m-%d")
    df[date] =  pd.to_datetime(df[date],errors = "coerce")

In [14]:
df.rename(columns = {"Row ID+O6G3A1:R6":"Row ID"},inplace= True)

In [15]:
df.drop(columns=["Row ID"],inplace=True)

In [16]:
df.insert(0,"Row ID",range(1,len(df) +1))

In [17]:
df.columns = df.columns.str.replace(" ","_")

In [19]:
df.rename(columns = {"sub-category":"sub_category"},inplace = True)
df

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Profit,Returns,Payment_Mode
0,1,CA-2019-160304,2019-01-01,2019-07-01,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.940,1,28.2668,0.0,Online
1,2,CA-2019-160304,2019-02-01,2019-07-01,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,East,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.940,3,38.2668,0.0,Online
2,3,CA-2019-160304,2019-02-01,2019-07-01,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,East,TEC-PH-10000455,Technology,Phones,GE 30522EE2,231.980,2,67.2742,0.0,Cards
3,4,CA-2019-125206,2019-03-01,2019-05-01,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,West,OFF-ST-10003692,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.460,2,28.6150,0.0,Online
4,5,US-2019-116365,2019-03-01,2019-08-01,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Central,TEC-AC-10002217,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.080,2,-5.2640,0.0,Online
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,5897,CA-2020-143259,NaT,2021-03-01,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,East,FUR-BO-10003441,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Fully Ass...",213.136,4,12.1176,0.0,COD
5897,5898,CA-2020-115427,NaT,2021-03-01,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,West,OFF-BI-10002103,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",295.904,2,4.5188,1.0,Online
5898,5899,CA-2020-156720,NaT,2021-03-01,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,388.024,3,-0.6048,0.0,Online
5899,5900,CA-2020-143259,NaT,2021-03-01,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,462.776,3,19.7910,0.0,COD
5900,5901,CA-2020-151450,NaT,2021-04-01,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,2975.510,3,-0.6048,0.0,COD

In [ ]:
#LOADING THE DATA IN SQL
pip install sqlalchemy pymysql

In [ ]:
from sqlalchemy import create_engine
import urllib.parse

password = urllib.parse.quote_plus("Shreda@7991")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost/super_store_data"
)

In [ ]:
df.to_sql("super_store", con=engine, if_exists="replace", index=False)